In [1]:
#numpy== immutable,to calcuale numerical data


In [2]:
import numpy as np

In [3]:
ar=np.arange(100,500,10)

In [4]:
ar

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490])

In [5]:
type(ar)

numpy.ndarray

In [7]:
ar.shape

(40,)

In [8]:
ar.ndim

1

In [9]:
ar.dtype

dtype('int32')

In [10]:
li=[i for i in range(1,100)]

In [11]:
ar=np.array(li,dtype=np.float32)

In [12]:
ar

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.], dtype=float32)

In [19]:
ar=np.array(li,dtype=np.float32,ndmin=3)

In [20]:
ar

array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
         25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36.,
         37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
         49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60.,
         61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
         73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83., 84.,
         85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96.,
         97., 98., 99.]]], dtype=float32)

In [21]:
ar.shape

(1, 1, 99)

In [22]:
ar.reshape(11,3,3)

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]],

       [[37., 38., 39.],
        [40., 41., 42.],
        [43., 44., 45.]],

       [[46., 47., 48.],
        [49., 50., 51.],
        [52., 53., 54.]],

       [[55., 56., 57.],
        [58., 59., 60.],
        [61., 62., 63.]],

       [[64., 65., 66.],
        [67., 68., 69.],
        [70., 71., 72.]],

       [[73., 74., 75.],
        [76., 77., 78.],
        [79., 80., 81.]],

       [[82., 83., 84.],
        [85., 86., 87.],
        [88., 89., 90.]],

       [[91., 92., 93.],
        [94., 95., 96.],
        [97., 98., 99.]]], dtype=float32)

In [23]:
ar.resize(33,3)

In [24]:
ar

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.],
       [22., 23., 24.],
       [25., 26., 27.],
       [28., 29., 30.],
       [31., 32., 33.],
       [34., 35., 36.],
       [37., 38., 39.],
       [40., 41., 42.],
       [43., 44., 45.],
       [46., 47., 48.],
       [49., 50., 51.],
       [52., 53., 54.],
       [55., 56., 57.],
       [58., 59., 60.],
       [61., 62., 63.],
       [64., 65., 66.],
       [67., 68., 69.],
       [70., 71., 72.],
       [73., 74., 75.],
       [76., 77., 78.],
       [79., 80., 81.],
       [82., 83., 84.],
       [85., 86., 87.],
       [88., 89., 90.],
       [91., 92., 93.],
       [94., 95., 96.],
       [97., 98., 99.]], dtype=float32)

In [ ]:
s=b'hello_world'
a=np.frombuffer()

In [3]:
import numpy as np

In [4]:
var=range(1,100,3)

In [7]:
ar=np.fromiter(var,dtype=np.float)

In [8]:
ar

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73., 76.,
       79., 82., 85., 88., 91., 94., 97.])

In [6]:
ar=np.array(var)

In [9]:
ar

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73., 76.,
       79., 82., 85., 88., 91., 94., 97.])

In [10]:
ar=np.zeros((4,5),dtype=np.int32)

In [11]:
ar

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
ar=np.ones((4,5),dtype=np.int32)

In [13]:
ar

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
ar=np.empty((4,5),dtype=np.int32)

In [15]:
ar

array([[4128860, 6029375, 3801155, 5242972, 7274610],
       [7471207, 7143521, 6357060, 6357108, 4259932],
       [6357102, 7274595, 6553710, 3342433, 7077980],
       [6422633, 7667804, 6881390, 7602292, 7536741]])

In [16]:
ar=np.arange(0,20).reshape(4,5)

In [17]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
ar[1]

array([5, 6, 7, 8, 9])

In [19]:
ar[0]

array([0, 1, 2, 3, 4])

In [20]:
ar[3]

array([15, 16, 17, 18, 19])

In [21]:
ar[3][3]

18

In [22]:
ar[3][2]

17

In [23]:
ar[0][4]

4

In [24]:
ar[1][4]

9

In [25]:
ar[1:3]                                   #from 1 row to 3-1=2

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
ar[1:3,2:4]                         #here 1st for row and 2nd for column.....here 2:4 means from 2 to 4-1=3

array([[ 7,  8],
       [12, 13]])

In [32]:
ar[1:3,2:4] = 0                       

In [33]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  0,  0,  9],
       [10, 11,  0,  0, 14],
       [15, 16, 17, 18, 19]])

In [31]:
ar[ar%2==0]
#ar[ar%2 != 0] = 1

array([ 0,  2,  4,  6,  0,  0, 10,  0,  0, 14, 16, 18])

In [36]:
ar[ar%2==0]=4

In [37]:
ar

array([[ 4,  1,  4,  3,  4],
       [ 5,  4,  4,  4,  9],
       [ 4, 11,  4,  4,  4],
       [15,  4, 17,  4, 19]])

In [39]:
ar=np.linspace(500,600,100).reshape(20,5)                     #reshape(20,5)-->means 20 rows and 5 clumns
print(ar)
print(ar[ar%2 != 0].sum())
print(ar[ar%2 == 0].sum())                                     #here count only 500 and 600 and generate 1100.0---->

[[500.         501.01010101 502.02020202 503.03030303 504.04040404]
 [505.05050505 506.06060606 507.07070707 508.08080808 509.09090909]
 [510.1010101  511.11111111 512.12121212 513.13131313 514.14141414]
 [515.15151515 516.16161616 517.17171717 518.18181818 519.19191919]
 [520.2020202  521.21212121 522.22222222 523.23232323 524.24242424]
 [525.25252525 526.26262626 527.27272727 528.28282828 529.29292929]
 [530.3030303  531.31313131 532.32323232 533.33333333 534.34343434]
 [535.35353535 536.36363636 537.37373737 538.38383838 539.39393939]
 [540.4040404  541.41414141 542.42424242 543.43434343 544.44444444]
 [545.45454545 546.46464646 547.47474747 548.48484848 549.49494949]
 [550.50505051 551.51515152 552.52525253 553.53535354 554.54545455]
 [555.55555556 556.56565657 557.57575758 558.58585859 559.5959596 ]
 [560.60606061 561.61616162 562.62626263 563.63636364 564.64646465]
 [565.65656566 566.66666667 567.67676768 568.68686869 569.6969697 ]
 [570.70707071 571.71717172 572.72727273 573.737

In [3]:
import numpy as np

In [4]:
a=np.arange(0,20).reshape(4,5)
b=np.arange(0,20,4)

In [5]:
a                        #2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
b                            #1D

array([ 0,  4,  8, 12, 16])

In [7]:
a+b

array([[ 0,  5, 10, 15, 20],
       [ 5, 10, 15, 20, 25],
       [10, 15, 20, 25, 30],
       [15, 20, 25, 30, 35]])

In [8]:
c=np.arange(0,20,5).reshape(4,1)
c

array([[ 0],
       [ 5],
       [10],
       [15]])

In [9]:
a+c

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [31]:
a=np.arange(0,12).reshape(3,4)
b=np.arange(1,9).reshape(4,2)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
b[:,0] = [i for i in range(1,5)]

In [28]:
b[:,1] = [i for i in range(5,9)]

In [29]:
b

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])